#########################################################
# Ingress for Moleculer API Gateway
#########################################################
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
spec:
  ingressClassName: traefik
  rules:
  - host: baoleme.xyz
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: api
            port:
              number: 3000

# ==============================
# Ingress 路由规则
# ==============================
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
spec:
  ingressClassName: traefik
  rules:
    - host: baoleme.xyz
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 3000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: auth-ingress
spec:
  ingressClassName: traefik
  rules:
    - host: baoleme.xyz
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: auth-mail
                port:
                  number: 3000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mail-ingress
spec:
  ingressClassName: traefik
  rules:
    - host: baoleme.xyz
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: auth-mail
                port:
                  number: 3000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-ingress
spec:
  ingressClassName: traefik
  rules:
    - host: baoleme.xyz
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: minio
                port:
                  number: 9001

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cart-history-item-ingress
spec:
  ingressClassName: traefik
  rules:
    - host: baoleme.xyz
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: cart-history-item
                port:
                  number: 3000
          - path: /history
            pathType: Prefix
            backend:
              service:
                name: cart-history-item
                port:
                  number: 3000
          - path: /item
            pathType: Prefix
            backend:
              service:
                name: cart-history-item
                port:
                  number: 3000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: order-shop-ingress
spec:
  ingressClassName: traefik
  rules:
    - host: baoleme.xyz
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: order-shop
                port:
                  number: 3000
          - path: /shop
            pathType: Prefix
            backend:
              service:
                name: order-shop
                port:
                  number: 3000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: address-ingress
spec:
  ingressClassName: traefik
  rules:
    - host: baoleme.xyz
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: address
                port:
                  number: 3000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: user-review-ingress
spec:
  ingressClassName: traefik
  rules:
    - host: baoleme.xyz
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: user-review
                port:
                  number: 3000
