apiVersion: apps/v1
kind: Deployment
metadata:
  name: oss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oss
  template:
    metadata:
      labels:
        app: oss
    spec:
      containers:
      - name: oss
        image: docker.io/library/baoleme-backend-microservices:latest
        imagePullPolicy: Never
        envFrom:
        - configMapRef:
            name: common-env
        env:
        - name: SERVICES
          value: "oss"
        ports:
        - containerPort: 3000
          name: http
        resources:
          limits:
            cpu: "200m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "256Mi"

---
#########################################################
# Service for OSS Service
#########################################################
apiVersion: v1
kind: Service
metadata:
  name: oss
spec:
  selector:
    app: oss
  ports:
  - port: 3000
    targetPort: 3000
    name: http

---
# =========================
# OSS service HPA
# =========================
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: oss-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: oss
  minReplicas: 1
  maxReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
---
# ==============================================
# Minio for development environment
# ==============================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: quay.io/minio/minio:latest
        args: ["server", "--console-address", ":9001", "/data"]
        env:
        - name: MINIO_ROOT_USER
          value: "31b4134289454f089eb1554a81c6bbef"
        - name: MINIO_ROOT_PASSWORD
          value: "fc59412342fa488991ff65e94fbea656"
        ports:
        - containerPort: 9000
        - containerPort: 9001
        volumeMounts:
        - name: minio-data
          mountPath: /data
      volumes:
      - name: minio-data
        persistentVolumeClaim:
          claimName: minio-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  selector:
    app: minio
  ports:
  - name: api
    port: 9000
    targetPort: 9000
  - name: console
    port: 9001
    targetPort: 9001
---
# ===============================
# NATS Message Broker
# ===============================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
      - name: nats
        image: nats:2
        ports:
        - containerPort: 4222
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "50m"
            memory: "32Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: nats
spec:
  selector:
    app: nats
  ports:
  - port: 4222
    targetPort: 4222
