#########################################################
# Database Secrets
#########################################################
apiVersion: v1
kind: Secret
metadata:
  name: auth-mail-db-credentials
type: Opaque
data:
  POSTGRES_USER: YXV0aG1haWx1c2Vy     # base64 encoded "authmailuser"
  POSTGRES_PASSWORD: YXV0aG1haWxwYXNz  # base64 encoded "authmailpass"
---
apiVersion: v1
kind: Secret
metadata:
  name: address-db-credentials
type: Opaque
data:
  POSTGRES_USER: YWRkcmVzc3VzZXI=     # base64 encoded "addressuser"
  POSTGRES_PASSWORD: YWRkcmVzc3Bhc3M=  # base64 encoded "addresspass"
---
apiVersion: v1
kind: Secret
metadata:
  name: cart-history-item-db-credentials
type: Opaque
data:
  POSTGRES_USER: Y2FydGhpc3Rvcnl1c2Vy     # base64 encoded "carthistoryuser"
  POSTGRES_PASSWORD: Y2FydGhpc3RvcnlwYXNz  # base64 encoded "carthistorypass"
---
apiVersion: v1
kind: Secret
metadata:
  name: order-shop-db-credentials
type: Opaque
data:
  POSTGRES_USER: b3JkZXJzaG9wdXNlcg==     # base64 encoded "ordershopuser"
  POSTGRES_PASSWORD: b3JkZXJzaG9wcGFzcw==  # base64 encoded "ordershoppass"
---
apiVersion: v1
kind: Secret
metadata:
  name: user-review-db-credentials
type: Opaque
data:
  POSTGRES_USER: dXNlcnJldmlld3VzZXI=     # base64 encoded "userreviewuser"
  POSTGRES_PASSWORD: dXNlcnJldmlld3Bhc3M=  # base64 encoded "userreviewpass"
