#########################################################
# Database Secrets
#########################################################
apiVersion: v1
kind: Secret
metadata:
  name: auth-db-credentials
type: Opaque
data:
  POSTGRES_USER: YXV0aHVzZXI=     # base64 encoded "authuser"
  POSTGRES_PASSWORD: YXV0aHBhc3M=  # base64 encoded "authpass"
---
apiVersion: v1
kind: Secret
metadata:
  name: mail-db-credentials
type: Opaque
data:
  POSTGRES_USER: bWFpbHVzZXI=     # base64 encoded "mailuser"
  POSTGRES_PASSWORD: bWFpbHBhc3M=  # base64 encoded "mailpass"
---
apiVersion: v1
kind: Secret
metadata:
  name: address-db-credentials
type: Opaque
data:
  POSTGRES_USER: YWRkcmVzc3VzZXI=     # base64 encoded "addressuser"
  POSTGRES_PASSWORD: YWRkcmVzc3Bhc3M=  # base64 encoded "addresspass"
