services:
  baoleme-backend-api:
    image: baoleme-backend-microservices:latest
    ports:
      - 3000:3000
    env_file: ci-compose.env
    environment:
      - SERVICES=api,hello
    depends_on:
      nats:
        condition: service_started
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/api/hello']
      interval: 30s
      timeout: 5s
      retries: 5

  baoleme-backend-mail:
    image: baoleme-backend-microservices:latest
    env_file: ci-compose.env
    environment:
      - SERVICES=mail
    depends_on:
      nats:
        condition: service_started

  baoleme-backend-oss:
    image: baoleme-backend-microservices:latest
    env_file: ci-compose.env
    environment:
      - SERVICES=oss
    depends_on:
      minio:
        condition: service_healthy
      nats:
        condition: service_started

  baoleme-backend-auth:
    image: baoleme-backend-microservices:latest
    env_file: ci-compose.env
    environment:
      - SERVICES=auth
    depends_on:
      postgres:
        condition: service_healthy
      nats:
        condition: service_started

  baoleme-backend-user-address:
    image: baoleme-backend-microservices:latest
    env_file: ci-compose.env
    environment:
      - SERVICES=user,address
    depends_on:
      postgres:
        condition: service_healthy
      nats:
        condition: service_started

  baoleme-backend-shop-item:
    image: baoleme-backend-microservices:latest
    env_file: ci-compose.env
    environment:
      - SERVICES=shop,item
    depends_on:
      postgres:
        condition: service_healthy
      nats:
        condition: service_started

  baoleme-backend-order:
    image: baoleme-backend-microservices:latest
    env_file: ci-compose.env
    environment:
      - SERVICES=order
    depends_on:
      postgres:
        condition: service_healthy
      nats:
        condition: service_started

  baoleme-backend-cart:
    image: baoleme-backend-microservices:latest
    env_file: ci-compose.env
    environment:
      - SERVICES=cart
    depends_on:
      postgres:
        condition: service_healthy
      nats:
        condition: service_started

  baoleme-backend-history:
    image: baoleme-backend-microservices:latest
    env_file: ci-compose.env
    environment:
      - SERVICES=history
    depends_on:
      postgres:
        condition: service_healthy
      nats:
        condition: service_started

  baoleme-backend-review:
    image: baoleme-backend-microservices:latest
    env_file: ci-compose.env
    environment:
      - SERVICES=review
    depends_on:
      postgres:
        condition: service_healthy
      nats:
        condition: service_started

  baoleme-backend-recommended:
    image: baoleme-backend-microservices:latest
    env_file: ci-compose.env
    environment:
      - SERVICES=recommended
    depends_on:
      nats:
        condition: service_started

  minio:
    image: quay.io/minio/minio:latest
    command: server /data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 30s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:17
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres', '-d', 'baoleme_test']
      interval: 30s
      timeout: 5s
      retries: 5

  nats:
    image: nats:2