name: Microservice Merge Check

on:
  push:
    branches:
      - microservice-refactor
    paths-ignore:
      - '**.md'
      - 'docs/**'
  workflow_dispatch:

jobs:
  merge-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag baoleme-backend-microservices:latest

      - name: Run docker-compose
        run: |
          docker compose -f scripts/ci-compose.yml up -d --wait

      - name: Run tests
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres
        run: |
          npm install --include=dev
          npm run test:integration
