name: Microservice Deploy

on:
  push:
    branches:
      - microservice-refactor
    paths-ignore:
      - '**.md'
      - 'docs/**'
  workflow_dispatch:
    

env:
  IMAGE_NAME: baoleme-backend-microservices:${{ github.sha }}
  IMAGE_NAME_LATEST: baoleme-backend-microservices:latest

defaults:
  run:
    shell: pwsh

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag $env:IMAGE_NAME
        docker image tag $env:IMAGE_NAME $env:IMAGE_NAME_LATEST
    
    - name: Prepare environment
      run: cp docker-compose.env scripts/docker-compose.env

    - name: Run Docker compose
      run: |
        docker compose -f scripts/ci-compose.yml up -d --wait
    # - name: Run tests
    #   run: |
    #     docker container exec baoleme-backend-microservices-api
    - name: Save Docker image
      run: |
        docker image save $env:IMAGE_NAME_LATEST | gzip > baoleme-backend-microservices.tar.gz
    
    - name: Prepare deploy files
      run: |
        mkdir -p deploy
        cp baoleme-backend-microservices.tar.gz deploy/
        cp docker-compose.yml deploy/
        cp docker-compose.env deploy/
        cp k8s.yaml deploy/

    - name: Upload Docker image
      uses: actions/upload-artifact@v4
      with:
        name: deploy-package
        path: deploy/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download deployment package
      uses: actions/download-artifact@v4
      with:
        name: deploy-package
        path: deploy

    - name: Upload files to server
      uses: wlixcc/SFTP-Deploy-Action@v1.2.6
      with:
        username: ${{ vars.SSH_USER }}
        server: ${{ vars.SSH_HOST }}
        port: ${{ vars.SSH_PORT }}
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        local_path: './deploy'
        remote_path: /home/ci
    - name: Restart backend service
      uses: appleboy/ssh-action@v1
      with:
        username: ${{ vars.SSH_USER }}
        host: ${{ vars.SSH_HOST }}
        port: ${{ vars.SSH_PORT }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/ci/deploy
          # 停止并删除现有容器
          docker compose down --remove-orphans || true
          # 清理未使用的镜像和数据卷
          docker system prune -f
          # 加载本地镜像
          docker image load -i baoleme-backend-microservices.tar.gz
          # 启动新服务
          docker compose up -d --wait
          # 检查服务状态
          # docker compose ps
